### ISSUE TITLE
Selecting label causes the shapes underneath to be selected

### ISSUE THREAD

**Issue by zthomas** [pikasojs/pikaso#10]
When the users moves a label on top of an existing shape, mouse events seems to be propagating to the underlying shape. Backspace keystroke used to edit the inline text will cause the shape beneath it to be deleted accidentally. 

## Steps to Reproduce
In the demo, https://pikaso.netlify.app/
1. move the "Try Picaso!" on top of the image of the chin scratching couple 
2. double click the label to try to enter inline edit mode (it actually takes two consequtive double clicks to enter that mode)
3. you'll notice that the background image becomes selected
4. The label does go into inline edit mode however, when you try to press backspace to delete a character from the "Try Pikaso!" label it actually deletes the image underneath it. 

## Possible Solution
- I've forked the project and added `e.cancelBubble = true` in the [`inlineEdit` function](https://github.com/pikasojs/pikaso/blob/master/src/shape/models/LabelModel/index.ts#L105) that's triggered on a `dblclick`. This does prevent the double click event from propagating. 
- However, subsequent single clicks to move the text cursor still need to stop from bubbling. I couldn't find a solution for that at the time of writing.

**Comment by raminious** [comment]
@zthomas Thanks. I'll take a look at the bug this weekend. please push the reproducible bug in a repo if it's possible.

**Comment by raminious** [comment]
@zthomas thanks for the great and detailed description. it helped me to identify and fix the bug pretty quick. The fix published on NPM.
Also, you can take a look at the latest version here https://pikaso.surge.sh

**Comment by zthomas** [comment]
Awesome! Looks great to me. 🙌
