### ISSUE TITLE
Allow export to svg

### ISSUE THREAD

**Issue by anthonycamilleri** [pikasojs/pikaso#114]
Additionally to import/export as JS and export to png, it would be really useful to export to a format such as SVG. 

Our particular use case imagines using Pikaso as a template builder, with further transformations done on the template in the backend of the application. In such a case, SVG makes for a great standardised wrapper to move the template around.

We have been trying to get svg export to work with the react-konva-to-svg library, but can't quite seem to be able to integrate the two.

**Comment by raminious** [comment]
Thanks @anthonycamilleri 
I'll take a look into that soon

**Comment by raminious** [comment]
I did some research and development, but exporting all components to SVG isn’t feasible at this time.​
