### ISSUE TITLE
Shapes: Snap shape to other shapes/guidelines

### ISSUE THREAD

**Issue by kanarelo** [pikasojs/pikaso#27]
I know this is a must need for designers. But just a nice to have, so, low priority.

As seen in this [Konva.js](https://konvajs.org/docs/sandbox/Objects_Snapping.html) demo, the ability to precisely snap to other shapes, helps designers create pixel perfect designs in a shorter cycles.

We can add following functionalities as part of this:
- Align to horizontal centre
- Align to vertical centre

I am not sure where the code goes, will leave that to your judgement.

**Comment by raminious** [comment]
I love it

**Comment by raminious** [comment]
released in [v2.4.0](https://github.com/pikasojs/pikaso/releases/tag/v2.4.0)
