### ISSUE TITLE
Keyboard: Formal Keyboard API/Map

### ISSUE THREAD

**Issue by kanarelo** [pikasojs/pikaso#29]
This is just an accessibility feature, though, low priority, it goes well with #28, so, I will add it for discussion.

We might need a formal keyboard api, that will help access all core functionalities via the Keyboard. Especially features like zoom in/out.

Currently, we can focus on generic keyboard shortcuts; avoiding mac shortcuts, and implementing 

```
SHORTCUTS

Undo
Redo

Canvas
Zoom in
Zoom out
Zoom to actual size
Zoom to fit canvas

Layers
Duplicate layer
Constrain proportions

RESIZE LAYER
Delete Layer
Nudge position by 1px
Nudge position by 10px
Bring forward
Send backward
```

**Comment by raminious** [comment]
I thought about this issue for several hours. I believe it should handle outside the Pikaso library.
I think [https://github.com/jaywcjlove/hotkeys](https://github.com/jaywcjlove/hotkeys) is good library to do that

**Comment by kanarelo** [comment]
Cool, will handle this in the header app.
