### ISSUE TITLE
I want to create a shape inside another shape 

### ISSUE THREAD

**Issue by osamatan125** [pikasojs/pikaso#44]
i am creating a rect. of full with and height according to window/document.
now i have no space outside that rect. to draw an other one.
basically it will be like room and i will create multiple object like a new rect. or a line over it.
so in this case i want to know how could that be possible.
or
or
or there should be a way that a when you hover over an object  selection cursor appears so it can be edited.
but cursor should only come when you click on any object not hovering over it.
when you click on object then you can resize that object.

**Comment by raminious** [comment]
released with v2.3.0
https://github.com/pikasojs/pikaso/releases/tag/v2.3.0
