### ISSUE TITLE
Show height and width on x and y axis of a shape while drawing it.

### ISSUE THREAD

**Issue by osamatan125** [pikasojs/pikaso#55]
Sir I want to show the height width of a shape while I am drawing it on x and y axis of the shape, and it should vary when I increase or decrease height width while drawing, also it should vanish after I have completed drawing the shape.

**Comment by osamatan125** [comment]
![pikaso_screenshot](https://user-images.githubusercontent.com/97286025/159059752-1bbf622d-bf2f-4858-a103-62f6ba2db380.PNG)
  

like this...

**Comment by raminious** [comment]
released with [https://github.com/pikasojs/pikaso/releases/tag/v2.5.0](https://github.com/pikasojs/pikaso/releases/tag/v2.5.0)
