### ISSUE TITLE
Ability to resize Imported Image

### ISSUE THREAD

**Issue by kanarelo** [pikasojs/pikaso#59]
**Is your feature request related to a problem? Please describe.**
Currently, when you load from an Image from a URL, the size of the image overrides all other settings of width and height. This breaks the UI, as the developer is forced to resize the image before importing it into Pikaso.

**Describe the solution you'd like**
If we can have the `loadFromUrl` or `setImageFromUrl` to accept a `resize` value, which can be a percentage of its aspect ratio, or actual `width` and `height` values that can be respected.

**Describe alternatives you've considered**
- Resizing the image
- Dynamically recalculate the image at runtime

---
The image imported should not be larger than scene area, unless explicitly zoomed.

**Comment by kanarelo** [comment]
This issue can be solved by use of CSS... Let me see if this is a valiable option...

**Comment by raminious** [comment]
@kanarelo it would be great if you provide a [codesandbox](https://codesandbox.io/) that reproduces the problem

**Comment by kanarelo** [comment]
@raminious You can check it here... https://codesandbox.io/s/trusting-antonelli-vx4i5w?file=/src/index.js

I should be able to import and center any size of image, larger than or equal to the scene area.

**Comment by raminious** [comment]
With version 2.6.0, Pikaso will support different modes of resizing when loading a background image.
`'auto' | 'resize' | 'cover' | 'contain' | 'stretch'` are the size options. To maintain backward compatibility, it will be `resize` by default 

Example:

```ts
editor.loadFromUrl('<url>') // resizes canvas to to file's size by default

editor.loadFromUrl('<url>', {
  size: 'cover'
})

editor.loadFromFile('<File>', {
  size: 'stretch'
})

```

https://github.com/pikasojs/pikaso/commit/017e81f7f3293cabbde3a76c93f3626e532c37da

**Comment by raminious** [comment]
released https://github.com/pikasojs/pikaso/releases/tag/v2.6.0
