### ISSUE TITLE
Background Image and Overlay settings

### ISSUE THREAD

**Issue by kanarelo** [pikasojs/pikaso#60]
**Is your feature request related to a problem? Please describe.**
Currently, once you have set the background items to be selectable; 

```typescript
editor.board.background.image.isSelectable = true;
editor.board.background.overlay.isSelectable = true;
```
There is no way of setting if the image is `resizable` or `draggable` on creation.

**Describe the solution you'd like**
- The overlay and image should be grouped by default, and draggable & resizable together.
- The overlay and image should not be able to [resize](https://konvajs.org/docs/select_and_transform/Resize_Limits.html)/[drag](https://konvajs.org/docs/sandbox/Limited_Drag_And_Resize.html) past the size of the board, unless the user wants that (advanced).
- The image/overlay can be `selectable` and `not draggable` at the same time.

**Describe alternatives you've considered**
- I have considered having this out of Pikaso, but its an important feature especially for graphic designers.

**Additional context**
https://codesandbox.io/s/59-ability-to-resize-imported-image-forked-idxry0

**Comment by raminious** [comment]
@kanarelo Adding this feature to the core will introduce a lot of confusion. Therefore, at this point I will not include it.
Also this is not a blocker. You could use `editor.shapes.image.insert` to create a selectable and draggable background image.

You could use such a snippet if you want to have a draggable image and overlay together

```
const background = editor.shapes.image.insert('<url>')
const overlay = editor.shapes.rect.insert({ /* config */ })

editor.board.groups.attach([background, overlay], 'background')
```

ps: `editor.board.background.overlay.isSelectable = true` is a bad practice in Pikaso
