### ISSUE TITLE
NodeJS Env Support

### ISSUE THREAD

**Issue by ehussain** [pikasojs/pikaso#64]
**Is your feature request related to a problem? Please describe.**
I would like to implement NodeJS Environment support so that something like this can be implemented
https://github.com/konvajs/konva#4-nodejs-env

We are looking to generate the image dynamically by replacing certain tokens in JSON. 
We would be generating canvas and drawings that would be exported as JSON later on.
Later on we could replace some placeholder texts in JSON file to generate the fully dynamic image using node js environment.

**Describe the solution you'd like**
Konva supports the stage creation in nodejs environment. It would be really nice to have something like that in Pikaso.
https://github.com/konvajs/konva#4-nodejs-env

Example code in Konva 

```
const Konva = require('konva/cmj').default;
let fs = require('fs');

let jsonContent = fs.readFileSync(process.cwd() + "/stage.json").toString();
jsonContent = jsonContent.replace("{{first_name}}", "Hussain");

var stage = Konva.Node.create(jsonContent);

let base64Data = stage.toDataURL();
base64Data = base64Data.replace(/^data:image\/png;base64,/, "");
fs.writeFileSync(process.cwd() + "/stage.png", base64Data, 'base64');
```

**Comment by raminious** [comment]
@ehussain Please help me to understand something.
Is there any advantage to using Pikaso over Konva in a NodeJs environment. Pikaso's most useful features (like History, Selection, and ...) are useless in non-interactive environments. I like to you what motivates you to use Pikaso in such environment, it'd motivates me to spend more time to make Pikaso compatible with Nodejs

**Comment by ehussain** [comment]
Hi @raminious 

Exactly, because Pikaso comes with built in features with History, selection, export and various shapes it makes it lot easier to integrate on UI. Because of many built in features it saves lot of time for UI integration however project also has backend requirement to generate image in Node JS environment. So for only that reason I have to compromise all good features of Pikaso and build everything from scratch using Konva which makes it very inconvenient for me.

**Comment by raminious** [comment]
great. I added this to the roadmap

**Comment by raminious** [comment]
released in https://github.com/pikasojs/pikaso/releases/tag/v2.7.0
