### ISSUE TITLE
Allow resizing label similar to "text" shape.

### ISSUE THREAD

**Issue by amanver16** [pikasojs/pikaso#66]
This is a feature request to allow users to resize "label" similar to "text". If possible allow to edit "text" as it is already resizable.
More details I have posted in [this discussion](https://github.com/pikasojs/pikaso/discussions/65)

**Comment by raminious** [comment]
The feature is done will be released with version 2.6.0

The following configuration should be followed to enable resizing from different aspects:

```ts
editor.shapes.label.insert({
    container: {/* config */},
    tag: {/* config */},
    text: {/* config */},
    config: {
      keepScale: false|true, // By setting keepScale to false, the default scaling behavior will be disabled
      transformer: {
        keepRatio: true, // keepRatio set to true to maintain scaling when scaling from corners
        enabledAnchors: ['middle-left', 'middle-right', 'bottom-right'] // Here are all the options available https://konvajs.org/api/Konva.Transformer.html#enabledAnchors__anchor
      }
    }
  })
```

All options for [`Konva.Transformer`](https://konvajs.org/api/Konva.Transformer.html) are available through `transformer`

**Comment by raminious** [comment]
released https://github.com/pikasojs/pikaso/releases/tag/v2.6.0

**Comment by amanver16** [comment]
I have tested it. Everything works like a charm now.
Thank you so much,
