### ISSUE TITLE
Empower developers to maintain their own state representation

### ISSUE THREAD

**Issue by idfunctor** [pikasojs/pikaso#80]
I am implementing a complex drawing solution using Pikaso. Unfortunately, there doesn't seem to be anyway to reflect the drawn elements in state outside of Pikaso's internal state.
I need to keep the newly drawn items' information in my own component's state, however, it seems that there is no way to currently do it except doing editor.export.toJSON() and picking the latest item from there.
In the product I'm building, something you have drawn right now can be deleted by someone else sharing your session in the next second (just like any collaborative editing apps). For this reason, I must always keep a "clone" of Pikaso state in memory.

One way to do this is to constantly do editor.export.toJSON() on each and every event that the user is doing like adding/editing/removing/showing/hiding any node.
Do you think that that's the "right" way to do it? I wonder if it's good for performance when it comes to a board that has too many items rendered.

**Describe the solution you'd like**

I'm not sure if this is a good solution but maybe it would be a good idea to make `private nodeToObject` property of JsonExport class to be available as a standalone function, so that one can use it to mutate their state on each board event (by making sure that every "create" results in adding `nodeToObject(currentItem)` to custom state.

react-konva makes it really easy to have React state representing the shapes and mapping over them to draw Canvas items. This ensures that if some outside event or service deletes an object from the react state list, the canvas automatically makes that Konva node disappear. Of course, I will develop the reconciling (adding/removing specific nodes based on outside events) myself in the product's business logic for Pikaso,  but I only need your insight on what's the best way to maintain that state to begin with. That if exporting the whole board as JSON at every event is alright or should I be doing something else.

If there is a solution that you recommend which needs changes to Pikaso itself I would be happy to work on it.

**Comment by raminious** [comment]
@idfunctor Shapes can be accessed in two ways at the moment 

1- `editor.board.shapes` and `editor.board.activeShapes`
https://pikaso.app/api/classes/Board.html#activeShapes

2- define an event listener `editor.on('shape:create', (data) => {})`
https://pikaso.app/api/classes/Pikaso.html#on

Would you mind telling me if the current APIs cover this requirement or not. I am totally open to improving this part of the library
