### ISSUE TITLE
Import SvgModel, SvgDrawer

### ISSUE THREAD

**Issue by pierrick-cpc** [pikasojs/pikaso#94]
Can't import classes SvgModel & SvgDrawer

`import { SvgDrawer, SvgModel } from 'pikaso';`

My IDE automatically add these imports:
`import { SvgDrawer } from 'pikaso/esm/shape/drawers/SvgDrawer';
import { SvgModel } from 'pikaso/esm/shape/models/SvgModel';`

I got this error on compiling:
`Module not found: Error: Can't resolve 'pikaso/esm/shape/drawers/SvgDrawer'`

Maybe the SgvDrawer and SvgModel exports are missing in index.all.ts ?

**Additional context**
Use in Angular

**Version**
"pikaso": "^2.7.5"

**Comment by raminious** [comment]
Unfortunately, I ain't that familiar with Angular. Can you please fork this https://codesandbox.io/s/angular-example-pozt0q and provide a very minimum code that reproduces the error so I can take a look into that.

**Comment by raminious** [comment]
@pierrick-cpc I just released a new version that should fix the problem. Thank you for reporting the bug.
If the problem persists, please reopen the issue.

https://github.com/pikasojs/pikaso/releases/tag/v2.7.6
